services:
  brain-api:
    image: ants3107/brain-api:latest
    platform: linux/arm64
    build:
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - 8150:8000
    environment:
      - BB_USER_NAME=user
      - BB_PASSWORD=pass
  brain-mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=example-user
      - MONGODB_INITDB_ROOT_PASSWORD=example-pass

volumes:
  mongo-data: