[package]
name = "bb_eye"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
env_logger = "0.11.1"
log = "0.4.22"
sysinfo = "0.29.2" # or latest version
