services:
  eye-build-linux-arm64:
    platform: linux/arm64
    build:
      context: .
      args:
        - TARGET=aarch64-unknown-linux-gnu
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /app
  eye-build-linux-amd64:
    platform: linux/amd64
    build:
      context: .
      args:
        - TARGET=x86_64-unknown-linux-gnu
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /app
  eye-build-windows-amd64:
    platform: linux/amd64
    build:
      context: .
      args:
        - TARGET=x86_64-pc-windows-gnu
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /app

volumes:
  cargo-cache:
