services:
  face-ui:
    image: ants3107/face-ui:latest
    platform: linux/arm64
    build:
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
    environment:
      API_BASE: http://localhost:8000/ui
    ports:
      - 8160:3000
  