services:
  face-api:
    image: ants3107/face-ui:latest
    platform: linux/arm64
    build:
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - 8160:3000
  