name: Cross Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev
        export OPENSSL_DIR=/usr
        export PKG_CONFIG_ALLOW_CROSS=1
        export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc
        export CC_x86_64_unknown_linux_gnu=x86_64-linux-gnu-gcc
        export CXX_x86_64_unknown_linux_gnu=x86_64-linux-gnu-g++
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig

    - name: Install Cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build
      run: |
        cd eye
        cross build --release --target ${{ matrix.target }}

    - name: Package Binary
      run: |
        cd eye/target/${{ matrix.target }}/release
        if [[ "${{ matrix.target }}" == *"windows"* ]]; then
          zip bb_eye-${{ matrix.target }}.zip bb_eye.exe
          mv bb_eye-${{ matrix.target }}.zip ../../../
          mv bb_eye-${{ matrix.target }}.exe ../../../
        else
          tar czf bb_eye-${{ matrix.target }}.tar.gz bb_eye
          mv bb_eye-${{ matrix.target }}.tar.gz ../../../
          mv bb_eye ../../../bb_eye-${{ matrix.target }}
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bb_eye-${{ matrix.target }}
        path: |
          eye/bb_eye-${{ matrix.target }}.tar.gz
          eye/bb_eye-${{ matrix.target }}
          eye/bb_eye-${{ matrix.target }}.zip
          eye/bb_eye-${{ matrix.target }}.exe
